### ISSUE TITLE
[FEAT] Support modular install

### ISSUE THREAD

**Issue by asterkin** [BstLabs/py-clvm#13] opened 2022-03-28 14:06 UTC
clvm is a kind of swiss army knife tool for managing cloud VMs (as development remote desktops). As such it contains many features that bring in dependencies, some of them heavy. Ideally, we should be able to install just enough plugins(say supporting vscode) and ability to add more plugins via the same clvm cli. The fact, that it's the same pip3 install inside should not concern anybody.

**Comment by ShahriyarR** [comment] 2022-05-03 09:19
As we have concluded on only supporting vscode.
The issue is not relevant.
Closing.

**Closed by ShahriyarR** 2022-05-03 09:19 UTC
